# Generated by Django 5.0.7 on 2024-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='product',
            name='serialNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
