# Generated by Django 5.0.7 on 2024-08-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_delete_user_alter_product_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(),
        ),
    ]
